apiVersion: broker.amq.io/v2alpha1
kind: ActiveMQArtemisAddress
metadata:
  name: order-in-progress
  namespace: eda-demo
spec:
  addressName: order-in-progress
  queueName: order-in-progress
  routingType: anycast